artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://drive.google.com/file/d/1wwmvyPlvuJHn-wSHwr1856QGcywFafej/view?usp=drive_link
  raw_data_dir : artifacts/data_ingestion/raw_data
  raw_data_file : artifacts/data_ingestion/raw_data/raw_data.csv
  data_dir : Data/data.csv

data_validation:
  root_dir : artifacts/data_validation
  data_dir : artifacts/data_ingestion/raw_data/raw_data.csv
  validation_file : artifacts/data_validation/validation_status.txt

data_transformation:
  root_dir : artifacts/data_transformation
  data_dir : artifacts/data_ingestion/raw_data/raw_data.csv
  train_data_file : artifacts/data_transformation/train_data.csv
  test_data_file : artifacts/data_transformation/test_data.csv